spring:
  application:
    name: modul
  datasource:
    password: ${MODUL_DB_PASS}
    username: ${MODUL_DB_USER}
    url: jdbc:postgresql://modul-db:${PG_PORT}/${MODUL_DB}
  security:
    user:
      name: none
      password: none
      role: none
management:
  endpoints:
    web:
      base-path: /api/modul/v1/actuator
      exposure:
        include: "*"
server:
  port: ${PROD_SERVER_PORT}
  address: ${SERVER_ADRESS}
jwt:
  secret: ${JWT_SECRET}
kartei:
  api_url: https://studyhuppy.de/api/kartei/v1
auth:
  api-url: https://studyhuppy.de/api/auth/v1