spring:
  application:
    name: modul
  datasource:
    password: ${MODUL_DB_PASS}
    username: ${MODUL_DB_USER}
    url: jdbc:postgresql://localhost:${MODUL_DB_HOST_PORT}/${MODUL_DB}
  security:
    user:
      name: none
      password: none
      role: none
management:
  server:
    port: ${DEV_SERVER_PORT}
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: metrics, health, info, prometheus
  metrics:
    enable:
      all: true
  security:
    enabled: true
server:
  port: ${DEV_SERVER_PORT}
jwt:
  secret: ${JWT_SECRET}
kartei:
  api_url: http://localhost:9503/api/kartei/v1
auth:
  api-url:  http://localhost:9501/api/auth/v1