spring:
  application:
    name: modul
  datasource:
    password: ${MODUL_DB_PASS}
    username: ${MODUL_DB_USER}
    url: jdbc:postgresql://localhost:${MODUL_DB_HOST_PORT}/${MODUL_DB}
  security:
    user:
      name: none
      password: none
      role: none
  kafka:
    bootstrap-servers: localhost:10000
    consumer:
      group-id: studyhuppy-modul
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management:
  server:
    port: ${DEV_SERVER_PORT}
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: metrics, health, info, prometheus
  metrics:
    enable:
      all: true
  security:
    enabled: true
server:
  port: ${DEV_SERVER_PORT}
jwt:
  secret: ${JWT_SECRET}
kartei:
  api_url: http://localhost:9503/api/kartei/v1
auth:
  api-url:  http://localhost:9501/api/auth/v1